GET http://localhost:3000/api/stones

<> 2020-08-06T101641.200.json
<> 2020-07-28T083601.200.json



###
POST http://localhost:3000/api/stones
Content-Type: application/json
Authorization: Basic ZWRpdG9yOmVkaXRvcg==

{
  "name": "Normalny",
  "price": 10.99
}

<> 2020-08-07T104352.500.txt

###

POST http://localhost:3000/api/stones
Content-Type: application/json
Authorization: Basic ZWRpdG9yOmVkaXRvcg==

{
  "name": "Normalny",
  "price": 10.99
}



###

POST http://localhost:8080/api/stones
Content-Type: application/json
Authorization: Basic weong==

{
  "name": "Normalny",
  "price": 10.99
}


###
GET http://localhost:3000/
