GET http://localhost:3000/api/stones

<> 2020-08-06T101641.200.json
<> 2020-07-28T083601.200.json


###
GET http://localhost:3000/api/stones/2

<> 2020-08-06T101641.200.json
<> 2020-07-28T083601.200.json



###
POST http://localhost:3000/api/stones
Content-Type: application/json
Authorization: Basic ZWRpdG9yOmVkaXRvcg==

{
  "name": "Normalny",
  "color": "gray",
  "size" : 5
}

<> 2020-08-07T104352.500.txt



###
GET http://localhost:3000/
