apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: stones-ingres
  annotations:
    kubernetes.io/ingress.global-static-ip-name: demo-neffect-dev
    networking.gke.io/managed-certificates: demo-certificate
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: stones-web-service
              servicePort: 80
          - path: "/api/*"
            backend:
              serviceName: stones-server-service
              servicePort: 3000
          - path: "/sys/*"
            backend:
              serviceName: stones-server-service
              servicePort: 3000
