apiVersion: apps/v1
kind: Deployment
metadata:
  name: stones-server
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: stones-server
    spec:
      containers:
        - name: stones-server
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          readinessProbe:
            httpGet:
              path: /sys/healthCheck
              port: 3000
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 2000m
          volumeMounts:
            - name: oauth-secrets
              mountPath: "/securedEtc"
              readOnly: true
      volumes:
        - name: oauth-secrets
          secret:
            secretName: stones-secrets
  selector:
    matchLabels:
      app: stones-server
